import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FastNote",
  description: "Generated by create next app",
  icons: {
    icon: null,
  },
};

export default function layout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <SessionProvider>
          <Header />
          <div className="flex-1">
            <main className="mx-auto w-full">{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
